%YAML:1.0
# Hash params
bucket_count:      400000
bucket_size:       10
entry_count:       4000000
linked_list_size:  7
value_capacity:    100000

# SDF params
voxel_size:                0.008
sdf_upper_bound:           4.0
truncation_distance_scale: 0.01
truncation_distance:       0.02
weight_sample:             10
weight_upper_bound:        255

# Sensor params
fx:              481.2
fy:              -480
cx:              319.5
cy:              239.5
min_depth_range: 0.5
max_depth_range: 3.0
range_factor:    0.0002
height:          480
width:           640

# Raycaster params
min_raycast_depth:    0.5
max_raycast_depth:    5.5
raycast_step:         0.016
sample_sdf_threshold: 0.808
sdf_threshold:        0.800
enable_gradient:      1

max_vertex_count:     10000000
max_triangle_count:   10000000
use_fine_gradient:    0