%YAML:1.0

dataset_path:      "/home/wei/Work/data/TUM/rgbd_dataset_freiburg1_rpy/"

# Hash params
bucket_count:      100000
bucket_size:       10
count:       1000000
linked_list_size:  7
value_capacity:    40000

# SDF params
voxel_size:                0.008
sdf_upper_bound:           4.0
truncation_distance_scale: 0.04
truncation_distance:       0.08
weight_sample:             10
weight_upper_bound:        255

# Sensor params
fx:              517.3
fy:              516.5
cx:              318.6
cy:              255.3
min_depth_range: 0.5
max_depth_range: 3.0
range_factor:    0.0002
height:          480
width:           640

# Raycaster params
min_raycast_depth:    0.5
max_raycast_depth:    5.5
raycast_step:         0.016
sample_sdf_threshold: 0.808
sdf_threshold:        0.800
enable_gradient:      1

max_vertex_count:     1000000
max_triangle_count:   1500000